const foods = [
  {
    id: "1",
    name: "Meat Pizza",
    ingredients: "Sausage, pizza dough, bacon, pizza sauce, red pepper flakes",
    price: "150",
    image: require("../assets/meatPizza.png"),
    quantity: 0,
    like: 0,
  },
  {
    id: "2",
    name: "Cheese Pizza",
    ingredients: "Mushroom, pizza base, mozzarella, green pepper,",
    price: "120",
    image: require("../assets/cheesePizza.png"),
    quantity: 0,
    like: 0,
  },
  {
    id: "3",
    name: "Chicken Burger",
    ingredients:
      "Ground chicken, coleslaw, smoked paprika, red onion, olive oil",
    price: "80",
    image: require("../assets/chickenBurger.png"),
    quantity: 0,
    like: 0,
  },
  {
    id: "4",
    name: "Sushi Makizushi",
    ingredients: "Salmon Meat",
    price: "80",
    image: require("../assets/sushiMakizushi.png"),
    quantity: 0,
    like: 0,
  },
  {
    id: "5",
    name: "Idali",
    ingredients: "Split urad dal, urad dal, idli rice, thick poha, rock salt",
    price: "90",
    image: require("../assets/idli.jpg"),
    quantity: 0,
    like: 0,
  },
  {
    id: "6",
    name: "Dhossa",
    ingredients: "Urad dal, idli rice, thick poha, rock salt, methi dana",
    price: "120",
    image: require("../assets/dhossa.jpg"),
    quantity: 0,
    like: 0,
  },
  {
    id: "7",
    name: "Uttapam",
    ingredients: "Idli batter, vegan, red onion, tomatoes, green chilies",
    price: "80",
    image: require("../assets/uttapam.jpg"),
    quantity: 0,
    like: 0,
  },
  {
    id: "8",
    name: "Pav Bhaji",
    ingredients: "Pav bhaji masala, potatoes, green peas, butter, carrot",
    price: "90",
    image: require("../assets/pavbhaji.jpg"),
    quantity: 0,
    like: 0,
  },
  {
    id: "9",
    name: "Manchurian",
    ingredients: "Apple cider vinegar, soy sauce, spring onion, toasted sesame",
    price: "90",
    image: require("../assets/manchurian.jpg"),
    quantity: 0,
    like: 0,
  },
  {
    id: "10",
    name: "Sandwich",
    ingredients:
      "Whole wheat bread, tomato, lettuce, hot pepper sauce, ketchup",
    price: "50",
    image: require("../assets/sandwich.png"),
    quantity: 0,
    like: 0,
  },
  {
    id: "11",
    name: "Puff",
    ingredients:
      "Puff pastry sheets, garam masala powder, tomato, kasuri methi, olive oil",
    price: "50",
    image: require("../assets/puff.jpg"),
    quantity: 0,
    like: 0,
  },
  {
    id: "12",
    name: "Vadapav",
    ingredients: "Red chutney, fried green, potatoes, dinner rolls, gram",
    price: "50",
    image: require("../assets/vadapav.jpg"),
    quantity: 0,
    like: 0,
  },
];

export default foods;
